// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCovenantPath1.Data;

#nullable disable

namespace MyCovenantPath1.Migrations
{
    [DbContext(typeof(CovenantPathDbContext))]
    [Migration("20250316192934_DallenSecond")]
    partial class DallenSecond
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("MyCovenantPath1.Data.Church_Attendance", b =>
                {
                    b.Property<int>("ChurchAttID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipRN")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChurchAttID");

                    b.ToTable("Church_Attendances");
                });

            modelBuilder.Entity("MyCovenantPath1.Data.Goal", b =>
                {
                    b.Property<int>("GoalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoalDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipRN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GoalID");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("MyCovenantPath1.Data.Lesson", b =>
                {
                    b.Property<int>("LessonNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LessonNumberID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("MyCovenantPath1.Data.LessonTaught", b =>
                {
                    b.Property<int>("LessonsTaughtID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembershipRN")
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonsTaughtID");

                    b.ToTable("LessonsTaught");
                });

            modelBuilder.Entity("MyCovenantPath1.Data.Study", b =>
                {
                    b.Property<int>("StudyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipRN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudyMaterialLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudyID");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("MyCovenantPath1.Data.Temple_Attendance", b =>
                {
                    b.Property<int>("TempleAttID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipRN")
                        .HasColumnType("INTEGER");

                    b.HasKey("TempleAttID");

                    b.ToTable("Temple_Attendances");
                });

            modelBuilder.Entity("MyCovenantPath1.Data.User", b =>
                {
                    b.Property<int>("MembershipRN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MembershipRN");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
